/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionemploi;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Malik ibn Zeynab
 */
public class EspaceEntreprise extends javax.swing.JFrame {

    /**
     * Creates new form EspaceEntreprise
     */
    public EspaceEntreprise() {
        initComponents();
        setTitle("Espace des Entreprises");
        //setSize(950, 600);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/gestionemploi/Logo_Entreprise/jobs.png")).getImage());
        Afficher_Table_Demandeur();
    }
    int pos = 0;

    public ImageIcon ResizeImage(String cheminImage, byte[] photo) {
        ImageIcon monImage = null;

        if (cheminImage != null) {
            monImage = new ImageIcon(cheminImage);
        } else {
            monImage = new ImageIcon(photo);
        }

        Image img = monImage.getImage();
        Image img2 = img.getScaledInstance(label_photo.getWidth(), label_photo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }

    public ArrayList<Demandeur> getListDemandeur() {
        ArrayList<Demandeur> listDemandeur = new ArrayList<Demandeur>();
        Connection con = Connexion.BaseDeDonnee();
        Statement stat = null;
        ResultSet res = null;
        String sql = "SELECT * FROM demandeur";
        try {
            stat = con.createStatement();
            res = stat.executeQuery(sql);
            Demandeur demandeur;
            while (res.next()) {
                demandeur = new Demandeur(res.getInt("identifiant"), res.getBytes("photo"), res.getString("nomDemandeur"), res.getString("prenomDemandeur"),
                        res.getString("sexe"), res.getString("dateDeNaissance"), res.getString("nationalite"), res.getString("telephone"),
                        res.getString("adresse"), res.getString("diplome"), res.getString("anneeObtention"), res.getString("domaine"),
                        res.getString("statut"), res.getString("cv"), res.getString("emailDemandeur"));
                
                listDemandeur.add(demandeur);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return listDemandeur;
    }
    // Afficher le contenu de la base de donnée dans un JTable

    public void Afficher_Table_Demandeur() {

        ArrayList<Demandeur> list = getListDemandeur();
        DefaultTableModel model = (DefaultTableModel) table_demandeur.getModel();

//Effacer le contenu du JTable
        model.setRowCount(0);
//Creation du nombre de clonne en fonction du nombre d'attribut
        Object[] colonne = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            colonne[0] = list.get(i).getPrenom();
            colonne[1] = list.get(i).getNom();
            colonne[2] = list.get(i).getSexe();
            colonne[3] = list.get(i).getDomaine();

            model.addRow(colonne);
        }
    }

    public void Vu(int index) {

        txt_id.setText(Integer.toString(getListDemandeur().get(index).getIdentifiant()));
        txt_domaine.setText((getListDemandeur().get(index).getDomaine()));
        byte[] img = (getListDemandeur().get(index).getPhoto());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(label_photo.getWidth(), label_photo.getHeight(), Image.SCALE_SMOOTH));
        label_photo.setIcon(imageIcon);
        //System.out.println(image);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_demandeur = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        label_photo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txt_domaine = new javax.swing.JTextField();
        precedent1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 204, 173));
        jPanel1.setLayout(null);

        table_demandeur.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        table_demandeur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prenom", "Nom", "Sexe", "Domaine d'activité"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_demandeur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_demandeurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_demandeur);
        if (table_demandeur.getColumnModel().getColumnCount() > 0) {
            table_demandeur.getColumnModel().getColumn(0).setResizable(false);
            table_demandeur.getColumnModel().getColumn(1).setResizable(false);
            table_demandeur.getColumnModel().getColumn(2).setResizable(false);
            table_demandeur.getColumnModel().getColumn(2).setPreferredWidth(15);
            table_demandeur.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 60, 580, 350);
        jPanel1.add(jScrollBar1);
        jScrollBar1.setBounds(590, 240, 17, 48);

        label_photo.setText("                                        photo");
        jPanel1.add(label_photo);
        label_photo.setBounds(10, 60, 270, 210);

        jButton2.setBackground(new java.awt.Color(213, 173, 149));
        jButton2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton2.setText("Suivant");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(470, 430, 160, 40);

        jButton3.setBackground(new java.awt.Color(213, 173, 149));
        jButton3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton3.setText("Precedent");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(300, 430, 159, 40);

        jButton4.setBackground(new java.awt.Color(213, 173, 149));
        jButton4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionemploi/logout.png"))); // NOI18N
        jButton4.setText("Quiter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(770, 430, 110, 40);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 330, 50, 40);

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id);
        txt_id.setBounds(70, 330, 50, 40);

        jButton1.setBackground(new java.awt.Color(213, 173, 149));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton1.setText("< Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 100, 30);

        jButton5.setBackground(new java.awt.Color(213, 173, 149));
        jButton5.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton5.setText("Voir CV");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 280, 270, 30);

        txt_domaine.setEditable(false);
        txt_domaine.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jPanel1.add(txt_domaine);
        txt_domaine.setBounds(410, 20, 210, 30);

        precedent1.setBackground(new java.awt.Color(213, 173, 149));
        precedent1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        precedent1.setText("Supprimer");
        precedent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precedent1ActionPerformed(evt);
            }
        });
        jPanel1.add(precedent1);
        precedent1.setBounds(10, 430, 159, 40);

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel1.setText("Domaine :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 20, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_demandeurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_demandeurMouseClicked

        int index = table_demandeur.getSelectedRow();
        Vu(index);
    }//GEN-LAST:event_table_demandeurMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pos++;
        if (pos >= getListDemandeur().size()) {
            pos = getListDemandeur().size() - 1;
        }
        Vu(pos);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GestionEntreprise acceuil = new GestionEntreprise();
        acceuil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (txt_id != null) {
            int id = Integer.parseInt(txt_id.getText());
            CV_Demandeur cv = new CV_Demandeur();
            cv.AfficherCVdemandeur(id);
            //cv.Afficher();
            cv.setVisible(true);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pos--;
        if (pos < 0) {
            pos = 0;
        }
        Vu(pos);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void precedent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precedent1ActionPerformed
        Connection con = Connexion.BaseDeDonnee();
        PreparedStatement stat = null;
        ResultSet res = null;
        String id = txt_id.getText();
        JOptionPane jop = new JOptionPane();
        String passe = jop.showInputDialog(null, " Mot de passe !", "Administrateur !", JOptionPane.QUESTION_MESSAGE);
        if (passe.equals("secret")) {

        try {
            String sql = "DELETE FROM demandeur WHERE identifiant=? ";

            stat = con.prepareStatement(sql);
            stat.setString(1, id);
            stat.execute();
            Afficher_Table_Demandeur();
            //JOptionPane.showMessageDialog(null, "Demandeur supprimé !");
            // table_entreprise.setModel((TableModel) res);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {

            try {

                res.close();
                stat.close();
                con.close();

            } catch (Exception e) {

            }
        }
        }else JOptionPane.showMessageDialog(null, "Mot de passe incorrecte !");

    }//GEN-LAST:event_precedent1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspaceEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspaceEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspaceEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspaceEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspaceEntreprise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_photo;
    private javax.swing.JButton precedent1;
    private javax.swing.JTable table_demandeur;
    private javax.swing.JTextField txt_domaine;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
